### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by alphaleadership** [LordAlex2015/discord-backup-system#1]
sa crée pas les backup

**Comment by ArviXDev** [comment]
Bonjour, pouvez-vous décrire le bug?

**Comment by alphaleadership** [comment]
Les fichiers ne sont pas créé de qui rend impossible l'utilisation des commandes liée à votre module

**Comment by ArviXDev** [comment]
Suffit de update le module, j'ai fix le problème^^

**Comment by alphaleadership** [comment]
Ok avez vous test

**Comment by ArviXDev** [comment]
Oui, bien sûr

**Comment by alphaleadership** [comment]
Vu que maintenant ses loadbackup qui marche pas

**Comment by ArviXDev** [comment]
En quoi le load fonctionne pas?

**Comment by ArviXDev** [comment]
Mettez le load en mode debug (Regardez la doc), parfois c'est votre serveur discord qui se fait "vérouillé" par discord et je n'y suis pour rien
