### ISSUE TITLE
getAllBackups problème.

### ISSUE THREAD

**Issue by Wailrone** [LordAlex2015/discord-backup-system#2]
Lorsqu'on tente de get toutes les backups, si aucune backup n'est présente, alors il ne se passera rien et la fonction de retournera rien. Il suffit donc d'ajouter ligne 652 : 

`if (files.length < 1) resolve({
            backups: [],
            time_elapsed: 0,
            fetched_backups: 0
        })`

**Comment by ArviXDev** [comment]
fixed
