### ISSUE TITLE
TypeError: channel.permissionOverwrites.each is not a function

### ISSUE THREAD

**Issue by Justman10000** [LordAlex2015/discord-backup-system#4]
Hi, this error comes:

> TypeError: channel.permissionOverwrites.each is not a function

File:

src/main.js:120

**Comment by Justman10000** [comment]
@LordAlex2015

**Comment by NathanLFG** [comment]
I have de same error, did you find the solution?

**Comment by Justman10000** [comment]
@LordAlex2015

Is something done here too?

**Comment by Justman10000** [comment]
Meanwhile, Discord.js v14 is already out

**Comment by LordAlex2015** [comment]
I'm currently working on a discord.js v14 version
it will be out soon

**Comment by LordAlex2015** [comment]
The  V2 has been released, you can now use the new version
